version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: simple-docker-service-0affc9afce05
    IMAGE_TAG: latest
    CONTAINER_NAME: nginx  # <-- Replace with your actual ECS container name

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 081653453064.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo hello
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 081653453064.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 081653453064.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "081653453064.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

